### ISSUE TITLE
ValueError: No objects to concatenate in to_dataframe method

### ISSUE THREAD

**Issue by jurasan** [googleapis/python-bigquery-storage#27]
If you have a small query result set  and many streams, then often one of the reading streams doesn't get any pages to read (probably other streams get to read all the data before ??)

Pandas doesn't allow `concat` on empty list. `return pandas.concat(frames)`

In this case the following exception occurs 

```
File "***/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/reader.py", line 236, in to_dataframe
    return self.rows(read_session).to_dataframe(dtypes=dtypes)

File "***/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/reader.py", line 336, in to_dataframe
    return pandas.concat(frames)

File "***/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 255, in concat
    sort=sort,

File "***/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in __init__
    raise ValueError("No objects to concatenate")

ValueError: No objects to concatenate
```

**Comment by plamut** [comment]
I have yet to confirm this, but it sounds plausible, thanks for the report. The fix to this might be as straightforward as returning an empty DataFrame if there's nothing to concatenate.

**Comment by plamut** [comment]
@jurasan Reading all data through just one of the returned streams is probably not the cause, at least not according to the [docs](https://cloud.google.com/bigquery/docs/reference/storage/#create_a_session) (emphasis mine):

>  When a read session is created, the server determines the amount of data that can be read in the context of the session and creates one or more streams, each of which represents approximately the same amount of table data to be scanned. This means that, to read all the data from a table, **callers must read from all Stream identifiers returned in the ReadSession response. This is a change from earlier versions of the API**, in which no limit existed on the amount of data that could be read in a single stream context.

As I read it, the bolded part implies that every returned stream will get allocated at least some portion of the result set. However, after experimenting further I eventually reproduced the issue with a very restrictive row filter on the session on the session's `read_options`.

The `row_restriction` that I set filtered out almost all of the 10M+ rows that would otherwise be returned by the query. The backend returned five streams, but some of them ended up empty, and this is probably happening in your app, too.

With a consistent reproduction in place I can now work on a fix, stay tuned. :)
