### ISSUE TITLE
'Client' object has no attribute 'query'

### ISSUE THREAD

**Issue by joaoalveshenriques** [googleapis/python-bigquery-storage#343]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Hello! 

I have already searched for this on the internet and couldn't solve the issue. I tried to upgrade every package but its not working.

I want to get a BigQuery query to a pandas df (I can do it through pd.read_sql but I can't run that as a script on a SQL Server Agent Job), and tried several methods, the error is the same.

Using Google's tutorial, my code is the following:

```
bqclient = bigquery.Client.from_service_account_json('BIGQUERY_CREDENTIAL.json')

# Download query results.
query_string = """
MY QUERY
"""

dataframe = (
    bqclient.query(query_string)
    .result()
    .to_dataframe(
        # Optionally, explicitly request to use the BigQuery Storage API. As of
        # google-cloud-bigquery version 1.26.0 and above, the BigQuery Storage
        # API is used by default.
        create_bqstorage_client=True,
    )
)
print(dataframe.head())
```
And then I get the error:

`AttributeError: 'Client' object has no attribute 'query'`

Any suggestion?

**Comment by meredithslota** [comment]
Thank you for filing an issue! Can you link the tutorial you were using as well?

**Comment by meredithslota** [comment]
Without knowing which tutorial you were following, I can only guess at the solution but my guess is that you are trying to query using only the storage client, instead of the core BigQuery client. Here is a code sample showing querying to a Pandas DataFrame: https://cloud.google.com/bigquery/docs/samples/bigquery-query-results-dataframe — you need to import the core BigQuery client as described. Let us know if this does not solve your issue!
