### ISSUE TITLE
Bigquery Storage Read is failing when running inside Docker. But the same code is working when running outside docker.

### ISSUE THREAD

**Issue by bhargavasatyamani** [googleapis/python-bigquery-storage#775]
Bigquery storage read is giving EOFError when used inside a docker container. But the same code is working when run outside docker.

<img width="860" alt="image" src="https://github.com/googleapis/python-bigquery-storage/assets/19183658/7adb0379-614c-45e0-9bb9-24f7d4b6da28">

**Comment by bhargavasatyamani** [comment]
This issue occured when using "AVRO" as the data format. It worked fine with "ARROW" format

**Comment by Linchin** [comment]
Thank you @bhargavasatyamani for raising the issue. Since the same code works outside of docker, I think it's unlikely an issue with the client library. My guess is this has something to do with docker's file system, or permission setting of the file. If the error persists, I suggest you open an issue in the [fastavro repo](https://github.com/fastavro/fastavro), as this is where the EOFError is raised. 

I will close the issue, but please let us know if you have any further questions.
